---
platform: linux

image_resource:
  type: docker-image
  source: {repository: springcloud/pipeline-base}

inputs:
  - name: df-repo
  - name: version
  
outputs:
  - name: build-output

run:
  path: df-repo/ci/tasks/deploy-stream-task.sh
  
params:
  SOURCEAPP:
  SINKAPP:
  SCDF_COMMANDS:
