---
platform: linux

image_resource:
  type: docker-image
  source: {repository: springcloud/pipeline-base}

inputs:
  - name: df-repo
  - name: version
  
outputs:
  - name: build-output

run:
  path: df-repo/ci/tasks/build-artifact.sh
  
params:
  SUBPROJECT:
  ARTIFACT:
