resources:
- name: df-repo
  type: git
  source:
    uri: git@github.com:Pivotal-Field-Engineering/dataflowprimer
    branch: master
    private_key: {{df-private-key}}
    username: mwright-pivotal
    password: newuser1

- name: source-version
  type: semver
  source:
    endpoint: {{s3-endpoint}}
    bucket: df-pipeline-artifacts
    key: current-version
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
    initial_version: 1.0.8

#- name: sink-version
#  type: semver
#  source:
#    endpoint: {{s3-endpoint}}
#    bucket: df-pipeline-artifacts
#    key: current-version
#    access_key_id: {{s3-access-key-id}}
#    secret_access_key: {{s3-secret-access-key}}
#    initial_version: 1.0.8

- name: df-release
  type: s3
  source:
    bucket: df-pipeline-artifacts
    regexp: (?:source|sink)demo-(.*).jar
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
    endpoint: {{s3-endpoint}}

jobs:
- name: unit
  plan:
  - get: df-repo
    trigger: true
  - task: unit
    file: df-repo/ci/tasks/unit.yml
    config:
      params:
        SUBPROJECT: sourcedemo

- name: build-binary-sourceapp
  serial: true
  plan:
  - get: df-repo
    passed: [unit]
    trigger: true
  - get: source-version
    params: {bump: patch}
  - task: build-artifact
    file: df-repo/ci/tasks/build-artifact.yml
    params:
      SUBPROJECT: sourcedemo
      ARTIFACT: sourcedemo-*.jar
    timeout: 5m
  - put: df-release
    params: {file: build-output/sourcedemo-*.jar}
  - put: source-version
    params: {file: source-version/number}

#- name: build-binary-sinkapp
#  serial: true
#  plan:
#  - get: df-repo
#    passed: [unit]
#    trigger: true
#  - get: sink-version
#    params: {bump: patch}
#  - task: build-artifact
#    file: df-repo/ci/tasks/build-artifact.yml
#    params:
#      SUBPROJECT: sinkdemo
#      ARTIFACT: sinkdemo-*.jar
#    timeout: 5m
#  - put: df-release
#    params: {file: build-output/sinkdemo-*.jar}
#  - put: sink-version
#    params: {file: sink-version/number}
      
- name: acceptance-tests
  plan:
  - aggregate:
    - get: df-release
      passed: [build-binary-sourceapp]
      trigger: true
    - get: df-repo
      passed: [build-binary-sourceapp]
      trigger: true
  - task: deploy-to-cats
    file: df-repo/ci/tasks/push-df-server.yml
    config:
      params:
        API_ENDPOINT: https://api.cf.wrightcode.net
        USERNAME: mwright@pivotal.io
        PASSWORD: p1v0tal
        ORG: wright-org
        SPACE: CI
        HOST: df-cats
        DOMAIN: cf.wrightcode.net
  - task: cats
    file: df-repo/ci/tasks/cats.yml
    config:
      params:
        MUSIC_URL: http://df-cats.cf.wrightcode.net

- name: promote-to-uat
  plan:
  - aggregate:
    - get: df-release
      passed: [acceptance-tests]
      trigger: true
    - get: df-repo
      passed: [acceptance-tests]
      trigger: true
  - task: deploy-to-uat
    file: df-repo/ci/tasks/cf-deployment.yml
    config:
      params:
        API_ENDPOINT: https://api.cf.wrightcode.net
        USERNAME: mwright@pivotal.io
        PASSWORD: p1v0tal
        ORG: wright-org
        SPACE: uat
        HOST: df-uat

- name: manual-deploy-to-prod
  serial: true
  plan:
  - aggregate:
    - get: df-release
      passed: [promote-to-uat]
    - get: df-repo
      passed: [promote-to-uat]
  - task: deploy-to-prod
    file: df-repo/ci/tasks/cf-deployment.yml
    config:
      params:
        API_ENDPOINT: https://api.cf.wrightcode.et
        USERNAME: mwright@pivotal.io
        PASSWORD: p1v0tal
        ORG: wright-org
        SPACE: prod
        HOST: df-server
